# Generated by Django 3.1.1 on 2020-09-17 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='status',
        ),
    ]
